# Generated by Django 5.1.1 on 2024-09-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSU_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PSU_random',
            fields=[
                ('psu_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psu.psu_base')),
            ],
            bases=('psu.psu_base',),
        ),
        migrations.CreateModel(
            name='PSU_serial',
            fields=[
                ('psu_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psu.psu_base')),
                ('serial', models.CharField(max_length=200)),
            ],
            bases=('psu.psu_base',),
        ),
    ]
