# Generated by Django 5.1.1 on 2024-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('psu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psu_base',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='psu_random',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='psu_serial',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='psu_base',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
