# Generated by Django 5.1.1 on 2024-09-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0002_alter_psu_base_options_alter_psu_random_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu_serial',
            name='currentIN',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='currentOUT',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='fan_speed',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='powerIN',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='powerOUT',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='temperature1',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='temperature2',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='temperature3',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='voltageIN',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='psu_serial',
            name='voltageOUT',
            field=models.FloatField(default=-1),
        ),
    ]
