# Generated by Django 5.1.1 on 2024-09-18 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0003_psu_serial_currentin_psu_serial_currentout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu_base',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
