# Generated by Django 5.1.1 on 2024-09-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0004_psu_base_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PSU_random',
        ),
    ]
