# Generated by Django 5.1.1 on 2024-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu', '0005_delete_psu_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu_base',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
